{% set name = "propcache" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/propcache-{{ version }}.tar.gz
  sha256: 40d980c33765359098837527e18eddefc9a24cea5b45e078a7f3bb5b032c6ecf

build:
  number: 1
  noarch: python       # [use_noarch]
  track_features:      # [use_noarch]
    - propcache_no_compile  # [use_noarch]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv                                      # [not use_noarch]
    - {{ PYTHON }} -m pip install . --no-deps -vv  --config-settings=pure-python=true  # [use_noarch]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
  host:
    - python {{ python_min }}     # [use_noarch]
    - python                      # [not use_noarch]
  host:
    - python {{ python_min }}     # [use_noarch]
    - python                      # [not use_noarch]
    - expandvars
    - setuptools >=47
    - tomli
    - cython
    - pip
  run:
    - python >={{ python_min }}   # [use_noarch]
    - python                      # [not use_noarch]

test:
  imports:
    - propcache
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}     # [use_noarch]

about:
  home: https://github.com/aio-libs/propcache
  summary: Accelerated property cache
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - xhochy
