{% set name = "propcache" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/propcache-{{ version }}.tar.gz
  sha256: 3f77ce728b19cb537714499928fe800c3dda29e8d9428778fc7c186da4c09a64

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - expandvars
    - setuptools >=47
    - tomli  # [py<311]
    - cython
    - pip
  run:
    - python

test:
  imports:
    - propcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/propcache
  summary: Accelerated property cache
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - xhochy
